#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Darkness.Android.Resource", IsApplication=true)]

namespace Darkness.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int AgeList = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CharacterPortrait = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CreateUserButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LoadMainButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LoadUserButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mapMode = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Mute = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int settingMode = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int smithMode = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Splash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int storyMode = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int StoryModeButton = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int CreateAUsernameText = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int CreateUserButton = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int DisplayPortrait = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int DisplayUsername = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int DisplayVersion = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int LoadMainButton = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int LoadSettingsOverlay = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int LoadSmithMode = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int LoadUserButton = 2131165203;
			
			// aapt resource value: 0x7f070009
			public const int LoadUsernameButton = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int LoadUsernameText = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int Mute = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int PasswordText = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int StoryModeButton = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int Title = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int UserEmail = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int UserPassword = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int UserUsername = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int UsernameText = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int root_view = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharacterMode = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateUserName = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoadUserName = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlayerVersusPlayer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SettingsMode = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SmithMode = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Start = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int StoryMode = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int SelectAge = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int userName = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Base = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_StoryMode = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
