#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Darkness.Android.Resource", IsApplication=true)]

namespace Darkness.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CharacterPortrait = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CreateUserButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LoadMainButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LoadUserButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mapMode = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int settingMode = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int smithMode = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Splash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int storyMode = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int StoryModeButton = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int CreateAUsernameText = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int CreateUserButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int DisplayUsername = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int DisplayVersion = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int LoadMainButton = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int LoadUserButton = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int LoadUsernameButton = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int LoadUsernameText = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int PasswordText = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int ShowUsername = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int StoryModeButton = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Title = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int UsernameText = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharacterMode = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateUserName = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoadUsername = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlayerVersusPlayer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SettingsMode = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SmithMode = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Start = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int StoryMode = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int userName = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Base = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Theme_StoryMode = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
